---
collections:
  - name: amazon.aws
  - name: community.postgresql
#  - name: kubernetes.core
#  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.controller
  - name: awx.awx
  - name: infra.openshift_virtualization_migration
    version: v1.25.0
#  - name: https://github.com/redhat-cop/openshift_virtualization_migration.git
#    type: git
#    version: v1.25.0
