---
collections:
  # OpenShift & AAP Automation
  - name: kubernetes.core
  - name: community.okd
  - name: ansible.controller
    version: ">=4.5.0"

  # VMware Inventory & Migration
  - name: community.vmware
  - name: https://github.com/redhat-cop/openshift_virtualization_migration.git
    type: git
    version: main

  # Database Management
  - name: community.postgresql