---
all:

  children:
    mock:
      hosts:
        mock_tokyo:
        m_da:
    mock_tokyo:
      hosts:
        m-ty:
          ansible_host: localhost
          vsphere_host: 172.17.250.170
          friendly_name: "m-ty"
          mtv_ocp_short: "m-ty"
        secondaryvsphere.int.tt.local:
          friendly_name: "Not absolutely required"
    m_da:
      hosts:
        unknown.tt.local:
          friendly_name: 'm-da'
          mtv_ocp_short: 'm-da'
