download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/redhat-openshift-6.0.0.tar.gz
format_version: 1.0.0
name: openshift
namespace: redhat
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2026-08-18T06:24:45.486605Z'
  signature: '-----BEGIN PGP SIGNATURE-----


    iQIcBAABCAAGBQJqg/qrAAoJEOGkvXCKgoqtWO0P/jyEYabhuGhAa+I7nU8+0FyZ

    ZROFT3EXyJ7Om4GI/9Um15qd0eyja7+F1ZxSpZRDYj3WkSWJFyh7T06kJsWasBWm

    5iI06XTGIA/jmqsbbJ8x2AHgoLsl++XWF4nJuJ0OiT6w0/Rvyeum768Q+8PVbPx0

    i7XP8ihOuudr/h4wCad8Ha+MhOZLZ0EmkBbLztQ10fJRvgJAyuBsRvP5XdwQ5lKM

    Ab/JEJWMvjvefRzXGGHQla9YA5siQyKYDWabvYnBetUcChHrTSfpxOW8tT1ZP4Eg

    MzAzDsT/Iguo+ZvNPkCdPE9cZdyoJq11C8bPg+e8DW78azkNUEQsa3VBrjJ/9Npj

    wobCBHTzQUJM5HTwDWkoidKxMir2O1fymJDUN2AKq+RX9n7smAuSidwJ4j37n+w3

    YC2iqtAh9QHHWZRD8TNLd2K/SL2JfMF75Ry3CGUk88qzjzX9iew2hT3JF75hhFVg

    6I4dD9DgDjZgsp2wsxTS4CxWuY0yWkIVclFUhw4ZKaCRWWrVtVsGRBPN/axu5WRZ

    bT56xsBGIf2u/K9c93v1pL6DkOt+vfUK0ONHiVPQmtPTNCLTyfqnMC6diY3OgH0a

    NjAmOxw5dK/1SG1+VIo/9f3O+v5rWotN+QxLBmGHrfqpuMRc+tuWQtST9fk61GbK

    2q+qiTCrSvJaTeca1Su6

    =vv9D

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 6.0.0
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/redhat/openshift/versions/6.0.0/
