#SPDX-License-Identifier: MIT-0
---
# tasks file for mtv_checks
#
---
- name: Execute MTV Blocker Checks
  ansible.builtin.include_tasks: check_blockers.yml

# If we want to pre-schedule jobs
#- name: Schedule Migration Job in AAP
#  ansible.builtin.include_tasks: schedule_job.yml
