---
- name: prechecks
#  hosts: "{{ vms | default('localhost') }}"
  hosts: "localhost"
  gather_facts: no

#  environment:
#    K8S_AUTH_HOST: "{{ openshift_host }}"
#    K8S_AUTH_API_KEY: "{{ openshift_token }}"
#    K8S_AUTH_VERIFY_SSL: "false"

  vars:
    mtv_tt_debug: true
  vars_files:
    - "../vars/all.yml"
    - "../vars/{{ vms }}.yml"
    - "../vars/all_vault.yml" 

  tasks:
    - name: "Prechecks | debug"
      ansible.builtin.debug:
        msg:
          "mtv_ocp_short is {{ mtv_ocp_short }}"
      when:
        - mtv_tt_debug | default(false)
    - name: "Prechecks | module_defaults"
      module_defaults:
        group/k8s:
          host: "{{ openshift_host }}"
          api_key: "{{ openshift_token }}"
          validate_certs: false
    - name: "Prechecks | include_role"
      ansible.builtin.include_role:
        name: "../roles/ocp_nad"
      
  
#  pre_tasks:
#    - name: "Precheck playbook - ensure a limit is passed in"
#      ansible.builtin.assert:
#        that:
#          - ansible_limit is defined
#        fail_msg: "ERROR: You must provide a --limit when executing this playbook"
  

  
