---
- name: prechecks
  hosts: "{{ vms | default('localhost') }}"
  gather_facts: no

  vars_files:
    - "../vars/all_vault.yml" 
    - "../vars/{{ mtv_ocp_short | default('tbd') }}.yml"

#  pre_tasks:
#    - name: "Precheck playbook - ensure a limit is passed in"
#      ansible.builtin.assert:
#        that:
#          - ansible_limit is defined
#        fail_msg: "ERROR: You must provide a --limit when executing this playbook"
  roles:
  - "ocp_nad"
  

  
