---
- name: prechecks
#  hosts: "{{ vms | default('localhost') }}"
  hosts: "localhost"
  gather_facts: no

  environment:
    K8S_AUTH_HOST: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    K8S_AUTH_API_KEY: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
    K8S_AUTH_VERIFY_SSL: "false"

  vars:
    mtv_tt_debug: true
  vars_files:
    - "../vars/all_vault.yml" 
    - "../vars/{{ mtv_ocp_short | default('tbd') }}.yml"

#  pre_tasks:
#    - name: "Precheck playbook - ensure a limit is passed in"
#      ansible.builtin.assert:
#        that:
#          - ansible_limit is defined
#        fail_msg: "ERROR: You must provide a --limit when executing this playbook"
  roles:
    - role: "../roles/ocp_nad"
  

  
